name: Style

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependent software
        run: |
          conda info
          conda env update --file environment-dev.yml --name base

      - name: Install format dependencies
        run: |
          pip3 install clang-format==18.1.2 cmake_format==0.6.13 pyyaml

      - name: configure
        run: cmake -S. -Bbuild

      - name: check style
        run: cmake --build build --target check-format
